triton-inference-server/dali_backend

src/CMakeLists.txt

Assign local RPATH for libtriton_dali.so, so that it'll link to proper libdali*.so libs

---

src/dali_backend.cc

Add try/catch blocks, so that dali_backend doesn't fail with segfault, but meaningful error message

Better error handling

---

src/dali_executor/CMakeLists.txt

Removing LICENSE install

---

src/dali_executor/dali_executor.cc
src/dali_executor/pipeline_pool.h

Fix for: #22 
When an error occurs remove the pipelines that were invalidated. 

Remove invalid pipelines

---

docs/examples/resnet50_trt/client.py

Fixing RN50 TRT example. Fix for issue #44 

Fixing RN50 TRT example

---

.clang-format

This is an update to code formatting rules. I'm open to all suggestions about it, so please treat this PR as call-for-discussion :)

Code formatting strategy update

---

CMakeLists.txt
src/dali_backend.cc
src/dali_executor/dali_executor.cc
src/dali_executor/dali_pipeline.cc
src/dali_executor/io_descriptor.test.cc

Add -Wall to build options, fix errors

---

docs/examples/identity/identity_pipeline.py
docs/examples/identity/setup_identity_example.sh
docs/examples/inception_ensemble/inception_pipeline.py
docs/examples/inception_ensemble/setup_inception_example.sh
docs/examples/multi_input/multi_input_pipeline.py
docs/examples/multi_input/setup_multi_input_example.sh
docs/examples/perf_analyzer/decoding_pipeline.py
docs/examples/resnet50_trt/serialize_dali_pipeline.py
docs/examples/resnet50_trt/setup_resnet50_trt_example.sh
qa/L0_identity/model_repository/identity_pipeline.py
qa/L0_inception_ensemble/model_repository/inception_pipeline.py
qa/L0_multi_input/model_repository/multi_input_pipeline.py

Adjusting examples for DALI's v1.0 recommended API (decorator)

Adjust examples for DALI v1.0 API

---

README.md

This PR adjust README pipeline example to the decorator API.

Adjusting README example to DALI's decorator API

---

docker/Dockerfile.devel
docker/Dockerfile.release

Bump Tritonserver version to 21.05

---

qa/L0_many_versions/many_versions_client.py
qa/L0_many_versions/model_repository/addition_pipeline.py
qa/L0_many_versions/model_repository/dali_all/config.pbtxt
qa/L0_many_versions/model_repository/dali_latest/config.pbtxt
qa/L0_many_versions/model_repository/dali_specific/config.pbtxt
qa/L0_many_versions/setup.sh
qa/L0_many_versions/test.sh
src/dali_model.h

Add test for multiple model versions

---

qa/L0_multi_input/model_repository/dali_multi_input/config.pbtxt
qa/L0_multi_input/model_repository/multi_input_pipeline.py
qa/L0_multi_input/multi_input_client.py

Verify scalar input in a test. 

---

docker/Dockerfile.devel
docker/Dockerfile.release

Bump Triton version to 21.08

---

docker/Dockerfile.devel
docker/Dockerfile.release

Bump Triton version to 21.09

---

docker/Dockerfile.devel
docker/Dockerfile.release

Bump Triton image version to the latest.

Bump Triton version to 21.11

---

docker/Dockerfile.devel
docker/Dockerfile.release

Bump Triton version to 21.12

---

CMakeLists.txt
docker/Dockerfile.release

We shall turn `-Werror` off by default.

Turn `-Werror` off by default

---

docs/examples/resnet50_trt/client.py

Fixed the output time unit of ResNet50 example script.

Correct the output time unit of ResNet50 example script

---

docker/Dockerfile.devel
docker/Dockerfile.release

Bump Triton version

---

docker/Dockerfile.devel
docker/Dockerfile.release

Add updated keys to fix docker build.

Fix apt update in docker build

---

docker/Dockerfile.devel
docker/Dockerfile.release

Update Triton images version to 22.04

---

src/dali_executor/CMakeLists.txt

Yet another fix for Conda environment path

---

docker/Dockerfile.devel
docker/Dockerfile.release
qa/L0_perf_analyzer_example/test.sh

Bump triton version. Fix perf_analyzer test

---

README.md

Please check wording and clarity.

Add section about config auto-complete to README

---

qa/L0_autoconfig/client.py
qa/L0_autoconfig/model_repository/no_config_file.dali/1/dali.py
qa/L0_autoconfig/setup.sh

It extends the autoconfig test with a model without configuration file

Test autoconfig with no config file

---

src/dali_model_instance.cc
src/utils/triton.cc

This PR adds some more NVTX markers to the DALI Backend.

Add more NVTX markers

---

src/dali_model.h

This PR adds better handling of partially filled model config and fixes device selection when no devices are available.

Fix device selction

---

benchmarks/BM_efficientnet/Dockerfile.torch
benchmarks/BM_efficientnet/benchmark-cpu.sh
benchmarks/BM_efficientnet/benchmark.sh
docker/Dockerfile.devel
docker/Dockerfile.release
docs/examples/efficientnet/0001-Update-requirements-and-add-Dockerfile.bench.patch
tools/update_container_version.sh

This PR adds missing rules to container version update script.
Also, updates the container version to 24.06

Add more rules to container version update

---

README.md

So it can be consumed by the main documentation better.

Change the order of the title and disclaimer
