- CMakeLists.txt
- Dockerfile
- client/dali_grpc_client.py
- src/dali_backend.cc
- src/dali_backend.h
- src/dali_executor/dali_executor.cc
- src/dali_executor/dali_executor.h
- src/dali_executor/dali_pipeline.cc
- src/dali_executor/dali_pipeline.h
- src/dali_executor/executor.test.cc
- src/dali_executor/pipeline_group.cc
- src/dali_executor/pipeline_group.h
- src/dali_executor/pipeline_pool.h
- src/dali_executor/test/test_utils.h
- src/dali_executor/utils/utils.h
TODO:
A few things happen in this PR:
- DALI Backend from now on will gather time statistics and report them via clients
- Small description of the docker image, handy for development
- Code base has been formatted according to triton-inference-server practise
- Updating supplied client to `tritonserver:20.10-client-py3`
- Small fixes due to gcc upgrade (proper to ubuntu20)
> Capture time statistics & docs update

- src/dali_backend.h
mem_type and mem_type_id specifies the preferred value when TRITONBACKEND_OutputBuffer reads them as input
> Init TRITONBACKEND_OutputBuffer arguments that also serve as input

- README.md
- src/dali_backend.h
This PR updates docs with info of first `tritonserver` version `dali_backend` is available in and changes preferred output memory type from DALI backend to GPU
> Update docs & change preferred output memory type

- qa/L0_identity/test.sh
- qa/L0_inception_ensemble/test.sh
- qa/L0_multi_input/test.sh
Relates to !26
This PR aims at allowing to specify `address:port` of the server, where the tests are run.
Usage of bash idiom:
```bash
GRPC_ADDR='localhost:8001' bash test.sh
```
> Specify tritonserver address:port in test scripts

- docker/Dockerfile.devel
- docker/Dockerfile.release
Relates to !27
So far, when building out-of-tritonserver-source, `dali_backend` had only Debug build configuration. With this change, `Dockerfile.devel` contains still the development-helpful image (thus Debug conf with some tools installed) and `Dockerfile.release` contains Release configuration. This image is a base for running C++ tests in the CI.
> Dockerfile for release build

- docker/Dockerfile.devel
- docker/Dockerfile.release
At this point, we were picking upstream Triton API version for building dali_backend, while deploying dali_backend into the last released version of `tritonserver`. This spawned a problem, when upstream bumped up API version: `dali_backend` suddenly had API version `1.2`, while the image we're deploying to had still `1.0`. And `tritonserver` API version has to be higher or equal to backend API version. 
This PR allows to pick manually Triton API version when building `dali_backend`
> Pick Triton version during docker image  build

- qa/L0_identity_cpu/identity_client.py
- qa/L0_identity_cpu/model_repository/dali_identity_cpu/config.pbtxt
- qa/L0_identity_cpu/model_repository/identity_pipeline.py
- qa/L0_identity_cpu/setup.sh
- qa/L0_identity_cpu/test.sh
- src/dali_backend.cc
- src/dali_executor/dali_executor.cc
- src/dali_executor/dali_executor.h
- src/dali_executor/dali_pipeline.cc
- src/dali_executor/dali_pipeline.h
One of Triton's modes of operation is that the server works for CPU only (e.g. when somebody runs `docker run` without `--gpus all` option). This PR adds test for this mode of operation and, since it doesn't work, fixes the bug.
Relevant for the review:
* The `L0_identity_cpu` test is copy-pasted `L0_identity` with one difference: DALI pipeline has `device_id=None` set.
> Fix CPU-only mode, add test for it

- src/dali_executor/dali_executor.cc
- src/dali_executor/dali_executor.h
- src/dali_executor/dali_pipeline.cc
- src/dali_executor/dali_pipeline.h
- src/dali_executor/executor.test.cc
Ouptut can now have multiple buffers. In that case, DALI pipeline will copy  output to an intermediate buffer. 
> Support chunked output buffers

- qa/L0_DALI_GPU_ensemble/client.py
- qa/L0_DALI_GPU_ensemble/model_repository/dali_1/config.pbtxt
- qa/L0_DALI_GPU_ensemble/model_repository/dali_2/config.pbtxt
Enable ragged batches in L0_DALI_GPU_ensemble.
`allow_ragged_batch` is an options that allows Triton to dynamically merge requests even if they contain samples with different shapes. 
To test that, I changed the test client to send concurrent requests with different sample shapes. 
I verified that those requests are indeed served together when the `allow_ragged_batch` is set to true.
> Test ragged batches.

- qa/L0_DALI_GPU_ensemble/model_repository/dali_1/pipeline.py
- qa/L0_DALI_GPU_ensemble/model_repository/dali_2/pipeline.py
- src/dali_executor/dali_executor.cc
- src/dali_executor/dali_executor.h
- src/dali_executor/dali_pipeline.cc
- src/dali_executor/dali_pipeline.h
- src/utils/utils.h
- src/utils/utils.test.cc
I check the backend of an external source to allocate an intermediate buffer on the same device. Due to that I can force no_copy mode when setting the input.
> Check external source backend to optimize intermediate buffer allocation.

- docs/examples/perf_analyzer/README.md
- docs/examples/resnet50_trt/README.md
Some of the readme files were outdated, since we changed the DALI API to the decorator. The decorator API was introduced in 21.04 and the container version we advertised was 20.12. This PR fixes the README.
> Update version in the README files

- CMakeLists.txt
- src/dali_executor/CMakeLists.txt
This PR allows specifying DALI version during dali_backend build is the following way:
```bash
cmake -D DALI_VERSION=1.4 [...]
```
> Specify DALI version as build argument

- CMakeLists.txt
In latest release, libcudacxx prompts a build error, that a typedef is unused:
```
/cuda/memory_resource:818:13: error: typedef ‘using __view1_t = class cuda::__4::basic_resource_view<_ResourcePointer, _Properties>’ locally defined but not used [-Werror=unused-local-typedefs]
818 |       using __view1_t = basic_resource_view;
```
This PR turns off this warning. It may be reverted, when the problem in libcudacxx is fixed.
> Working around build error from libcudacxx

- qa/L0_perf_analyzer_example/test.sh
This PR solves the problem of the `perf_analyzer_example` test, which has been sometimes failing. The testing conditions weren't correct - they assumed, that the throughput of the pipeline will always be in range `100..999 [ims/s]`. We should allow it to be `0..9999 [ims/s]`, as these are sane values in proper circumstances.
> Fix incorrect test definition for perf_analyer example

- CMakeLists.txt
- src/dali_backend.cc
- src/dali_executor/utils/utils.h
- src/dali_model_instance.cc
This PR adds NVTX markers for profiling DALI Backend with `nsys`. Also, creates a `DALI Backend` domain for the same usage.
Here's roughly, how it looks with the proposed markers:
> Add NVTX markers for DALI Backend

- qa/L0_perf_analyzer_example/test.sh
The previous test condition didn't forsee a situation, when measured throughput value does not have fractional part, e.g.:
```bash
Throughput: 76.8 infer/sec   -> test passed: matched the [0-9]{1,}\.[0-9] pattern
Throughput: 128 infer/sec    -> test failed: didn't match the pattern 
```
This PR adds this option.
> Update test condition for perf_analyzer_example

- CMakeLists.txt
Fixes the problem with warning propagated from `libcudacxx` to DALI and DALI Backend, which fails the build whenever `-Werror` has been turned on. Such situation might happen, since the parent project in CMake might do something along these lines:
```cmake
set(CMAKE_CXX_FLAGS "-Werror")
```
And this makes `-Werror` turned on, but by the parent project.
> Omit `unused-local-typedefs` warning

- CMakeLists.txt
- docker/Dockerfile.devel
- docker/Dockerfile.release
- src/dali_executor/CMakeLists.txt
This PR exposes in dcokerfiles the options to choose DALI version downloaded during the backend build.
> Add options to choose downloaded DALI version

- src/dali_executor/CMakeLists.txt
The previous way of passing CONDA_ENVIRONMENT_PATH from CMake to C++ didn't work correctly. I'm changing this to hardcode the path. I don't suspect this path to change anyway. If it changes, however, it will be an easy error to resolve.
> Hardcode Conda environment path

- CMakeLists.txt
- cmake/dalienv-extra_args.yml.in
- cmake/dalienv.yml.in
- src/dali_executor/CMakeLists.txt
Fixes the version of DALI package for DALI nightly. 
If during build DALI nightly is downloaded it chooses latest version instead of the version saved in DALI_VERSION. 
This PR also simplifies configuration of miniconda env. It leaves only one .in file and creates new CONF_* variables in cmake to correctly configure it.
> Fix version picking for DALI nightly. 

- src/config_tools/config_tools.cc
- src/config_tools/config_tools.h
- src/config_tools/config_tools.test.cc
It fixes handling outputs in auto-config implementation. 
It differentiates the behavior regarding inputs and outputs.
inputs:
The inputs in the config file are referenced by they names (they have to match the names given in the pipeline), so they can be freely reordered in the config file.
outputs:
Names of the outputs in the config file don't have to match the output names from the pipeline - they are rather used to override the names of the pipeline outputs. So in their case, order matters and is assumed to match the order of pipeline outputs. 
I extended the docstring of the config methods to contain this information. 
New methods:
`ReadMaxBatchSize` - reads and validates max batch size in the config
`ValidateConfig` - composition of ValidateInputs, ValidateOuptputs and …
> Fix outputs auto-config. Add max_batch_size validation

- qa/L0_config_validation/client.py
- qa/L0_config_validation/model_repository/model0_gpu_valid/config.pbtxt
- qa/L0_config_validation/model_repository/model1_gpu_invalid_i_type/config.pbtxt
- qa/L0_config_validation/model_repository/model2_gpu_invalid_o_ndim/config.pbtxt
- qa/L0_config_validation/model_repository/model3_cpu_valid/config.pbtxt
- qa/L0_config_validation/model_repository/model4_cpu_invalid_missing_output/config.pbtxt
- qa/L0_config_validation/pipeline_cpu.py
- qa/L0_config_validation/pipeline_gpu.py
- qa/L0_config_validation/setup.sh
- qa/L0_config_validation/test.sh
- src/config_tools/config_tools.cc
- src/config_tools/config_tools.h
- src/dali_executor/dali_pipeline.cc
- src/dali_executor/dali_pipeline.h
- src/dali_executor/utils/dali.h
- src/dali_model.cc
- src/dali_model.h
- src/dali_model_instance.h
Most of the volume of this PR is made by config files for test models - they're mostly just copy-paste with slight modifications (to introduce validation errors).
The significant parts are in files: 
- `dali_pipeline.h/cc` - methods for fetching inputs and outputs info from the pipeline.
- `dali_model.h` - instantiating pipeline (with choosing a device for that) and calling actual validation.
Tests are implemented in `client.py`. They try to load each of the prepared models and expect some kind of error.
> Validate config file against pipeline.

- qa/L0_autoconfig/client.py
- qa/L0_autoconfig/model_repository/partial_autoconfig/config.pbtxt
- src/config_tools/config_tools.cc
- src/config_tools/config_tools.test.cc
This PR extends auto-config to automatically enable dynamic batching in DALI models
> Enable dynamic batching when auto-completing model config

- CMakeLists.txt
- cmake/dalienv.yml.in
- docker/Dockerfile.release
- src/dali_executor/CMakeLists.txt
This PR updates the Python version used for creating conda environment for DALI to `3.10`. Additionally, extracts hardcoded values to a variable, so its easier in the future.
> Set python version to 3.10

- src/dali_executor/CMakeLists.txt
- when the conda environment is created it first uses
the existing packages in the system - for example
the one installed from Miniconda3-py38_4.12.0-Linux-x86_64.sh,
which may become outdated and vulnerable sooner or later.
This PR makes the environment to use the latest available
necessary packages when created to fix all CVEs that are fixable
by the update of the conda environment
Signed-off-by: Janusz Lisiecki <jlisiecki@nvidia.com>
> Update conda env packages during the creation

- src/dali_executor/CMakeLists.txt
- https://github.com/triton-inference-server/dali_backend/pull/166
added the update step for the created conda environment, however,
it uses the default conda channel which has outdated packages.
In this PR we move to conda-forge with the most up to date packages
Signed-off-by: Janusz Lisiecki <jlisiecki@nvidia.com>
>  Use conda-forge channel when updating conda environment

- src/config_tools/config_tools.cc
- src/config_tools/config_tools.h
- src/config_tools/config_tools.test.cc
- src/dali_model.h
When config is read by the tritonserver, there is no way to determine if max_batch_size was set to 0 by the user or was it just not provided. 
To workaround it, I manually load the config text file (if it exists) and parse it (to a limited level) to read the max_batch_size field. 
Signed-off-by: Rafal <rbanas@nvidia.com>
> Add ProtoBuf txt parsing to read max_batch_size

- src/dali_model.h
- src/error_handling.h
- src/utils/utils.h
Autoserialize was not working correctly due to race condition in tmp file naming. It was using a timestamp with a resolution of a second which caused conflicts between models.
To fix this, I changed the timestamp to maximal resolution of a monotonic clock (std::steady_clock).
> Fix tmp filename generation

- docs/examples/video_decode_remap/client.py
- docs/examples/video_decode_remap/model_repository/model.dali/1/dali.py
- src/dali_executor/dali_executor.cc
- src/dali_executor/dali_executor.h
- src/dali_executor/request_id.h
Should the `VideoInput` operator be properly working with `ExternalSource` in the same pipeline, DALI Backend needs to properly handle the `"depleted"` operator trace. This trace, defined in DALI, specifies when a given operator needs more data at the input. Refers to https://github.com/NVIDIA/DALI/pull/4794
> Add `"depleted"` operator trace handling

- CMakeLists.txt
- src/dali_model.h
- updates Catch2 to 2.13.9
- adds -Wno-free-nonheap-object compilation flag
as the compiler gets confused with SmallVector
memory management
- initializes dev_id variable
> Fix compilation with gcc 11.3

- benchmarks/BM_efficientnet/run-benchmarks.sh
- docs/examples/efficientnet/setup.sh
When running the `setup.sh` script using CUDA compat layer, `docker exec` proves to be problematic. It is better not to use `docker exec`, but to run `docker run` and then copy out the artifacts from the container.
> Working around incompatiblitiy in CUDA compat layer

- docs/tutorials/training_to_inference.md
This PR introduces a `training -> inference` tutorial. The use-case is based on Efficientnet model, presented both in DeepLearningExamples and DALI repository. All assumptions and explanations are provided inside.
> "Training to inference" tutorial

- src/dali_executor/dali_pipeline.cc
- src/dali_executor/dali_pipeline.h
- src/dali_executor/executor.test.cc
- src/dali_executor/utils/dali.h
- src/dali_model.cc
- src/dali_model.h
- src/dali_model_instance.h
The instance counting was bugged which caused multiple issues in CI.
Instead of just fixing it, I changed it to counting loaded models, instead of created pipelines because it better fits the semantics of release_after_unload option and might save us from unnecessary memory release, when pipelines are temporarily created and destroyed.
> Fix model counting

- benchmarks/BM_efficientnet/run-benchmarks-cpu.sh
- benchmarks/BM_efficientnet/run-benchmarks.sh
- benchmarks/BM_resnet50/run-benchmarks.sh
- qa/L0_dont_release_after_unload/test.sh
- qa/L0_release_after_unload/test.sh
Tests in CI that use perf_analyzer often fail because the measurements are not stable enough. This decreases that stability requirement
> Decrease stability requirements for perf_analyzer measurements

- CMakeLists.txt
- src/CMakeLists.txt
- src/dali_executor/CMakeLists.txt
This PR removes the conda package manager from the Triton system.
Conda has been used to isolate DALI wheel (which needs to be installed apart from being unpacked in the container) from the rest of Triton packages. Since we're moving away from this requirement, DALI can be installed bare-metal inside the Triton container and conda is no longer necessary.
> Remove conda package manager

- docker/Dockerfile.devel
- docker/Dockerfile.release
- src/CMakeLists.txt
- src/dali_executor/CMakeLists.txt
Due removing Conda dependency from `tritonserver` docker image, DALI Backend needs to modify how DALI wheel is installed within this docker image. We no longer can rely on `pip install` to do so - Triton's build system uses `builder` and `runtime` images. DALI Backend is built within the `builder` image and the necessary artifacts are copied to `runtime` image. Therefore DALI Backend will have the DALI wheel unpacked (and installed with CMake) together with all dependencies. Additionally, Triton's build system will set the `PYTHONPATH` variable (https://github.com/triton-inference-server/server/pull/7216), so that Python interpreter can pick proper DALI wheel.
> Change the way DALI is installed inside Triton

- src/dali_executor/CMakeLists.txt
Recently, `gast` extension (DALI dependency) changed its distribution pattern in PyPI. Previously it has beed distributed as a `whl` file, while currently it is a `tar.gz` file. Since DALI Backend approaches the DALI wheel installation in a specific way (extract + `PYTHONPATH` adjustment, instead of `pip install`), we need to augment DALI Backend build routines to accommodate for the new `gast` distribution method.
> Modify DALI wheel installation routine

- qa/L0_dont_release_after_unload/scripts/compare_memory_usage.py
Due to change in DALI (using nvImageCodec for image decoding), GPU memory consumption lowered when using `fn.decoders.image`. This PR adjusts the test values and makes the threshold related to the input data size.
> Lower test acceptance threshold

- qa/L0_autoconfig/client.py
- qa/L0_autoconfig/model_repository/full_autoconfig/1/dali.py
- qa/L0_autoconfig/model_repository/no_config_file.dali/1/dali.py
Autoconfig test was making assumptions on naming of the DALI outputs that weren't guaranteed which resulted in failing tests.
This PR names the pipeline outputs explicitly to make the test reliable.
> Explicitly name pipeline outputs in autoconfig tests

- benchmarks/BM_efficientnet/README.md
Point PA docs to new repo
Server changes: https://github.com/triton-inference-server/server/pull/7488
Client changes: https://github.com/triton-inference-server/client/pull/771
PA changes: https://github.com/triton-inference-server/perf_analyzer/pull/21
MA changes: https://github.com/triton-inference-server/model_analyzer/pull/925
PyTriton changes: https://github.com/triton-inference-server/pytriton/pull/80
Tutorial changes: https://github.com/triton-inference-server/tutorials/pull/105
> PA Migration: Update docs

- src/dali_executor/CMakeLists.txt
We need to be able to pass some additional options to pip install when installing DALI. It was missing from the CMake command.
> Fix passing extra options to pip install
